
export default {
    Scenes:[
        {
            id:"1",
            width:800,
            height:600,
            status:1,
            Monsters:[
                {
                    position:{x:400,y:200},
                    size:{w:50,h:50},
                    type:1,
                    img:"./src/images/devil.png"
                },
                {
                    position:{x:450,y:400},
                    size:{w:50,h:50},
                    type:2,
                    img:"./src/images/person.png"
                },
            ],
            Obstacles:[
                {
                    position:{x:100,y:100},
                    size:{w:100,h:100},
                    type:1,
                    img:"./src/images/Tree100.png"
                },
                {
                    position:{x:100,y:200},
                    size:{w:50,h:50},
                    type:2,
                    img:"./src/images/Stone50.png"
                },
                {
                    position:{x:200,y:300},
                    size:{w:50,h:50},
                    type:1,
                    img:"./src/images/Tree50.png"
                }
            ],
            doorway:{
                go:"2",
                position:{x:50,y:0},
                img:"./src/images/doorway.png"
            }
        },
        {
            id:"2",
            width:800,
            height:600,
            status:0,
            Monsters:[
                {
                    position:{x:300,y:300},
                    size:{w:50,h:50},
                    type:1,
                    img:"./src/images/devil.png"
                },
            ],
            Obstacles:[
                {
                    position:{x:250,y:450},
                    size:{w:50,h:50},
                    type:1,
                    img:"./src/images/Tree50.png"
                }
            ],
            doorway:{
                go:"1",
                // position:{x:750,y:550},
                position:{x:50,y:0},
                img:"./src/images/doorway.png"
            }
        }
    ],
    Hero:{
        type:1,
        position:{x:0,y:0},
        size:{w:50,h:50},
        img:"./src/images/hero.png"
    }
}