
export default {
    Scenes:[
        {
            width:800,
            height:600,
            status:1,
            Monsters:[

            ],
            Obstacles:[
                {
                    position:{x:100,y:100},
                    size:{w:50,h:50},
                    type:1
                },
                {
                    position:{x:100,y:200},
                    size:{w:50,h:50},
                    type:2
                },
                {
                    position:{x:200,y:300},
                    size:{w:50,h:50},
                    type:1
                }
            ]
        },
        {
            width:800,
            height:600,
            status:0,
            Monsters:[],
            Obstacles:[],
            Sections:[
                {
                    position:{x:0,y:0},
                    size:{w:400,h:300},
                },
                {
                    position:{x:400,y:0},
                    size:{w:400,h:300},
                },
                {
                    position:{x:0,y:300},
                    size:{w:400,h:300},
                },
                {
                    position:{x:400,y:300},
                    size:{w:400,h:300},
                }
            ]
        }
    ],
    Hero:{
        type:1,
        position:{x:0,y:0},
        size:{w:50,h:50},
        img:"./src/images/hero.png"
    }
}